version: "3.8"

services:
  backend:
    container_name: pantera-backend
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://mongo:27017/panteraProtocol
      SOLANA_RPC: https://api.mainnet-beta.solana.com
    depends_on:
      - mongo

  frontend:
    container_name: pantera-frontend
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    container_name: pantera-mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
